import type { ExpoConfig, ConfigContext } from "expo/config";

/**
 * App config. Three variants (master plan §24):
 *   development  co.pitchpage.app.dev   sits beside the real app on a device
 *   preview      co.pitchpage.app       TestFlight
 *   production   co.pitchpage.app       App Store
 *
 * APP_VARIANT is set by the EAS build profile; plain `expo start` is development.
 */
type Variant = "development" | "preview" | "production";
const VARIANT = (process.env.APP_VARIANT as Variant) ?? "development";
const IS_DEV = VARIANT === "development";

/** pitchpage.co is the one backend (master plan §24 — there is no staging). */
const SITE = "https://pitchpage.co";

export default ({ config }: ConfigContext): ExpoConfig => ({
  ...config,
  name: IS_DEV ? "PitchPage Dev" : "PitchPage",
  slug: "pitchpage",
  scheme: "pitchpage",
  version: "1.0.0",
  orientation: "portrait",
  // The New Architecture is the default in SDK 57, so it is not set here.
  userInterfaceStyle: "automatic",
  // Flat, high-resolution brand artwork with no alpha channel, as iOS requires.
  icon: "./assets/icon-v2.png",
  assetBundlePatterns: ["**/*"],
  ios: {
    supportsTablet: false, // iPhone only for 1.0 (decision Q7)
    bundleIdentifier: IS_DEV ? "co.pitchpage.app.dev" : "co.pitchpage.app",
    // PitchPage's Apple Developer team, so a project generated by prebuild signs
    // with it without anyone choosing a team in Xcode.
    appleTeamId: "S53D2H48PD",
    // A build made in Xcode needs a new number for every upload, and prebuild
    // --clean resets it, so the release command takes it from the environment
    // (IOS_BUILD_NUMBER=2 npm run ios:release). EAS builds keep their own count
    // (eas.json: appVersionSource "remote") and ignore this.
    ...(process.env.IOS_BUILD_NUMBER ? { buildNumber: process.env.IOS_BUILD_NUMBER } : {}),
    // The Sign in with Apple entitlement (guideline 4.8 — Google is offered).
    usesAppleSignIn: true,
    associatedDomains: ["applinks:pitchpage.co", "webcredentials:pitchpage.co"],
    config: {
      // Nothing in the app tracks people across other companies' apps or sites,
      // so there is no App Tracking Transparency prompt (master plan §21).
      usesNonExemptEncryption: false,
    },
    /*
     * Apple rejects an upload whose binary calls a "required reason" API without
     * declaring why (ITMS-91053). These four are reached by React Native itself
     * and by the Expo modules this app ships — storage, file system, image
     * picking, timing — so they are declared here for the whole app, each with
     * the reason that matches how it is used:
     *
     *   UserDefaults    CA92.1  read and written only by this app
     *   FileTimestamp   C617.1  files inside the app container
     *                   3B52.1  files the person picked themselves
     *   SystemBootTime  35F9.1  measuring elapsed time, never identity
     *   DiskSpace       E174.1  checking there is room before writing
     *                   85F4.1  so a too-large upload can say so
     *
     * Tracking is false: nothing here follows anyone across other companies'
     * apps or sites, which is also why there is no ATT prompt.
     */
    privacyManifests: {
      NSPrivacyTracking: false,
      NSPrivacyAccessedAPITypes: [
        {
          NSPrivacyAccessedAPIType: "NSPrivacyAccessedAPICategoryUserDefaults",
          NSPrivacyAccessedAPITypeReasons: ["CA92.1"],
        },
        {
          NSPrivacyAccessedAPIType: "NSPrivacyAccessedAPICategoryFileTimestamp",
          NSPrivacyAccessedAPITypeReasons: ["C617.1", "3B52.1"],
        },
        {
          NSPrivacyAccessedAPIType: "NSPrivacyAccessedAPICategorySystemBootTime",
          NSPrivacyAccessedAPITypeReasons: ["35F9.1"],
        },
        {
          NSPrivacyAccessedAPIType: "NSPrivacyAccessedAPICategoryDiskSpace",
          NSPrivacyAccessedAPITypeReasons: ["E174.1", "85F4.1"],
        },
      ],
    },
    infoPlist: {
      ITSAppUsesNonExemptEncryption: false,
      // "Save Image" in the share sheet writes the QR code to Photos, and iOS
      // stops the app if this string is missing when somebody picks it.
      NSPhotoLibraryAddUsageDescription:
        "PitchPage saves your page's QR code to your photo library.",
    },
  },
  android: {
    package: IS_DEV ? "co.pitchpage.app.dev" : "co.pitchpage.app",
    adaptiveIcon: {
      foregroundImage: "./assets/brand-mark.png",
      backgroundColor: "#F5EBDD",
    },
  },
  web: { bundler: "metro", output: "single", favicon: "./assets/favicon.png" },
  plugins: [
    "expo-apple-authentication",
    "expo-router",
    "expo-font",
    "expo-web-browser",
    // The app keeps its session in the keychain and never asks for Face ID,
    // so the Face ID text the plugin adds by default would be a request for
    // something the app doesn't use (App Review 5.1.1).
    ["expo-secure-store", { faceIDPermission: false }],
    // Said here rather than in infoPlist: Expo applies this plugin whether it
    // is listed or not, and only here can the microphone be turned off. The
    // camera takes a portrait and nothing else; the intro video comes from
    // Photos, so the app never records sound.
    [
      "expo-image-picker",
      {
        cameraPermission: "PitchPage uses your camera so you can take a portrait for your page.",
        photosPermission:
          "PitchPage uses your photo library so you can choose a portrait and an intro video for your page.",
        microphonePermission: false,
      },
    ],
    [
      "expo-splash-screen",
      {
        // Cream, the brand ground in both palettes' light mode (§19).
        backgroundColor: "#F5EBDD",
        // brand-mark.png is 128px, for the small in-app logo; drawn 200pt wide
        // here it is 600px on a 3x screen, so the splash has its own.
        image: "./assets/splash-mark.png",
        imageWidth: 200,
        // Mirror appDark.background: Expo's config loader cannot import the
        // app's TypeScript modules. app-config.test.ts guards against drift.
        dark: { backgroundColor: "#0A141F", image: "./assets/splash-mark.png", imageWidth: 200 },
      },
    ],
  ],
  experiments: { typedRoutes: true },
  extra: {
    variant: VARIANT,
    site: SITE,
    apiUrl: process.env.EXPO_PUBLIC_API_URL ?? `${SITE}/api/app/v1`,
    renderUrl: process.env.EXPO_PUBLIC_RENDER_URL ?? `${SITE}/app-render`,
    router: {},
    eas: { projectId: process.env.EAS_PROJECT_ID },
  },
});
