/**
 * A photograph of every template, as the website draws it.
 *
 * Generated by scripts/build-template-thumbnails.mjs — do not edit by hand.
 * The app renders thirty families through five archetypes and cannot draw the
 * difference between them, so the picker shows these instead of a swatch.
 * Re-run the script when a template changes on the web; nothing here updates
 * on its own, because the website's deploy does not either.
 */
export const TEMPLATE_THUMBNAILS: Record<string, number | undefined> = {
  "arch": require("../../assets/templates/arch.webp"),
  "arena": require("../../assets/templates/arena.webp"),
  "banner": require("../../assets/templates/banner.webp"),
  "broadsheet": require("../../assets/templates/broadsheet.webp"),
  "campus": require("../../assets/templates/campus.webp"),
  "console": require("../../assets/templates/console.webp"),
  "corporate": require("../../assets/templates/corporate.webp"),
  "estate": require("../../assets/templates/estate.webp"),
  "exhibit": require("../../assets/templates/exhibit.webp"),
  "feature": require("../../assets/templates/feature.webp"),
  "framed": require("../../assets/templates/framed.webp"),
  "interactive": require("../../assets/templates/interactive.webp"),
  "ledger": require("../../assets/templates/ledger.webp"),
  "letterhead": require("../../assets/templates/letterhead.webp"),
  "listing": require("../../assets/templates/listing.webp"),
  "momentum": require("../../assets/templates/momentum.webp"),
  "parcel": require("../../assets/templates/parcel.webp"),
  "personal": require("../../assets/templates/personal.webp"),
  "premium": require("../../assets/templates/premium.webp"),
  "recruit": require("../../assets/templates/recruit.webp"),
  "ring": require("../../assets/templates/ring.webp"),
  "scholar": require("../../assets/templates/scholar.webp"),
  "scorecard": require("../../assets/templates/scorecard.webp"),
  "sightline": require("../../assets/templates/sightline.webp"),
  "skyline": require("../../assets/templates/skyline.webp"),
  "split": require("../../assets/templates/split.webp"),
  "spotlight": require("../../assets/templates/spotlight.webp"),
  "startup": require("../../assets/templates/startup.webp"),
  "tiles": require("../../assets/templates/tiles.webp"),
  "trades": require("../../assets/templates/trades.webp"),
};
